//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddPatient()
        {
            this.Bills = new HashSet<Bill>();
            this.Labs = new HashSet<Lab>();
        }
    
        public int pid { get; set; }
        public string Pname { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public System.DateTime date_of_appointment { get; set; }
        public string email { get; set; }
        public string problem { get; set; }
        public string specialist { get; set; }
        public Nullable<int> staffid { get; set; }
        public string Staffname { get; set; }
        public string prescription { get; set; }
        public string report { get; set; }
        public int bill { get; set; }
        public Nullable<System.DateTime> Recheckupdate { get; set; }
        public Nullable<System.DateTime> Resheduledate { get; set; }
    
        public virtual Addstaff Addstaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab> Labs { get; set; }
    }
}
