//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Addstaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Addstaff()
        {
            this.AddPatients = new HashSet<AddPatient>();
        }


        //[DisplayName("Staff ID")]
        //[Required(ErrorMessage = "Required Field")]
        public int staffid { get; set; }
        public string Staffname { get; set; }
        public string Emailid { get; set; }
        public string MobileNo { get; set; }
        public string Gender { get; set; }

        //[DisplayName("Password")]
        //[Required(ErrorMessage = "Required Field")]
        //[DataType(DataType.Password)]
        public string Pwd { get; set; }

        public string Address { get; set; }
        public string Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddPatient> AddPatients { get; set; }
    }
}
