//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Bno { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> sno { get; set; }
        public System.DateTime BillingDate { get; set; }
        public string SName { get; set; }
        public int ConsultancyFee { get; set; }
        public string Test { get; set; }
        public int testFee { get; set; }
        public int subtotal { get; set; }
    
        public virtual AddPatient AddPatient { get; set; }
        public virtual Lab Lab { get; set; }
    }
}
