//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database1Entities : DbContext
    {
        public database1Entities()
            : base("name=database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddPatient> AddPatients { get; set; }
        public virtual DbSet<Addstaff> Addstaffs { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
    }
}
